### ISSUE TITLE
How to export last patch?

### ISSUE THREAD

**Issue by marcosps** [sjp38/hackermail#2]
For example, if there was only one single patch, and this patch is on top of the current ML, is there a way to export it, instead of the current 'hkml patch'?

I'm seriously considering stop using Evolution to manage MLs :)

**Comment by sjp38** [comment]
I think you could use `hkml export` (https://github.com/sjp38/hackermail/blob/master/USAGE.md#exporting-mails).  E.g.,

```
$ # Show the list of the mailing list, confirm the last mail (on top of the generated list) is the patch of your interest
$ hkml list $THE_MAILING_LIST
$
$ # export it into mbox format file
$ hkml export --range 0 1 my_patch.mbox
```

Then you could use any patch-handling tools with the exported file.

Yet another way is `hkml open`.  It shows specific mail in mbox-like format that most patch-handling tools also support.  So you can direct the `hkml open` output to a file.  E.g.,

```
$ hkml open 0 > my_patch.mbox
```

**Comment by marcosps** [comment]
The range 0 1 wasn't intuitive enough for me, but it makes sense. Also, I used the hkml patch on my git tree, and it worked as expected. That's good enough, thanks!

**Comment by sj-aws** [comment]
> The range 0 1 wasn't intuitive enough for me

Thank you for letting me know.  I will try to make it more intuitive :)

**Comment by marcosps** [comment]
> > The range 0 1 wasn't intuitive enough for me
> 
> Thank you for letting me know. I will try to make it more intuitive :)

Sorry, I sounded like I was mean. What I wanted to say is that I didn't thought about specifying range 0 to 1. This tool is really amazing, thanks for sharing!

**Comment by sj-aws** [comment]
No problem, it didn't sound like mean but very kindly letting me know the rooms for improvement.  I appreciate that :)
