### ISSUE TITLE
Have full YYYY/MM/DD when listing emails, rather than YY/MM/DD

### ISSUE THREAD

**Issue by marcosps** [sjp38/hackermail#5]
I find this confusing because at first, I thought that all emails were from day YY :P

I've tried to look at the code, but maybe I know exactly where to change it :)

**Comment by sjp38** [comment]
Hi Marcos, thank you so much for this nice suggestion .  I just made the change and pushed (https://github.com/sjp38/hackermail/commit/42d0147a8deac0ec70a115b1e222bc20b8eda4b0).  Please feel free to request any more improvement!

**Comment by marcosps** [comment]
Worked as a charm! You rock @sjp38 ! Thanks a lot!
